name: Scheduled Ping

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Website
        run: curl -sS "https://www.dondelodan.com/" > /dev/null
